version: 2
updates:
  # Enable version updates for npm in backend
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 10
    reviewers:
      - "APorkolab"
    assignees:
      - "APorkolab"
    commit-message:
      prefix: "backend"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  # Enable version updates for npm in frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 10
    reviewers:
      - "APorkolab"
    assignees:
      - "APorkolab"
    commit-message:
      prefix: "frontend"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
      - "security"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
    groups:
      security-updates:
        patterns:
          - "*"
        update-types:
          - "security"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 5
    reviewers:
      - "APorkolab"
    assignees:
      - "APorkolab"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 5
    reviewers:
      - "APorkolab"
    assignees:
      - "APorkolab"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Budapest"
    open-pull-requests-limit: 5
    reviewers:
      - "APorkolab"
    assignees:
      - "APorkolab"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "security"
